Add P2WSH handling to wallet database
stratisproject/StratisFullNode pull request #1105
Opened 2023-01-20 15:20 UTC by zeptin

2023-01-23 04:37 UTC, quantumagi commented
![image](https://user-images.githubusercontent.com/29645989/213966637-fa98eace-4658-4101-a73f-36c1b0b66cd5.png)

Why is the extract called twice? Can't we just yield return `txDestination` as before? Does the "change" have any effect?

2023-01-23 04:38 UTC, quantumagi requested changes
![image](https://user-images.githubusercontent.com/29645989/213966637-fa98eace-4658-4101-a73f-36c1b0b66cd5.png)

Why is the extract called twice? Can't we just yield return `txDestination`? Does the "change" have any effect?

Also under which circumstance can the `txDestination` length be 32?

```
        public WitKeyId(byte[] value)
            : base(value)
        {
            if(value.Length != 20)
                throw new ArgumentException("value should be 20 bytes", "value");
        }
```

2023-01-23 05:11 UTC, quantumagi approved these changes

2023-09-20 05:39 UTC, zeptin commented
In `release/1.6.0.0` we use `GetDestinationFromScriptPubKey` for all known script types. The P2WPKH/P2WSH differentiation is handled automatically by the `PayToWitTemplate` inside the `ScriptAddressReader`, rather than needing separate templates for the two individually.

2023-09-20 05:39 UTC, closed without merging