CirrusD should not kick members
stratisproject/StratisFullNode pull request #117
Opened 2020-10-23 14:31 UTC by fassadlr

@quantumagi the DI approach was too complicated and will require a lot of refactoring. This will work for now.

2020-10-23 14:32 UTC, fassadlr commented on src/Stratis.Bitcoin/Utilities/BinarySearch.cs
> +            var result = BinaryFindFirst(array, func, first, pivot);
@quantumagi the solution didnt build this my side. It was due to a coalescing feature only available in C#8

2020-10-23 18:45 UTC, zeptin approved these changes

2020-10-24 02:24 UTC, quantumagi commented on src/Stratis.Bitcoin.Features.PoA/Voting/IdleFederationMembersKicker.cs
> +            if (this.federationManager is FederationManager)
Perhaps a negative test would be better: e.g. `if (!(this.federationManager is CollateralFederationManager))` ?

2020-10-24 02:46 UTC, quantumagi commented
Something like this would be better:
```
        public static async Task MainAsync(string[] args)
        {
            try
            {
                var nodeSettings = new NodeSettings(networksSelector: CirrusNetwork.NetworksSelector,
                    protocolVersion: ProtocolVersion.CIRRUS_VERSION, args: args)
                {
                    MinProtocolVersion = ProtocolVersion.ALT_PROTOCOL_VERSION
                };

                ((PoAConsensusOptions)nodeSettings.Network.Consensus.Options).AutoKickIdleMembers = false;
```

2020-10-24 02:49 UTC, quantumagi requested changes
See comment.

2020-10-24 09:02 UTC, fassadlr commented
Cool will fix in the next hour :)

2020-10-24 10:45 UTC, fassadlr commented
@quantumagi done and tested 👍

2020-10-24 10:48 UTC, quantumagi approved these changes

2020-10-24 13:00 UTC, merged